(() => {
  if (!document.body.classList.contains('v2-dashboard-page')) return;
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const app=$('[data-dashboard-app]'); if(!app) return;

  if(!$('.syn-server-rail')){
    const rail=document.createElement('aside');
    rail.className='syn-server-rail';
    rail.innerHTML=`<button class="syn-rail-profile active" title="Mon compte"><span>PK</span></button><div class="syn-rail-sep"></div><button title="Serveur Démo" data-rail-server><img src="./assets/logo-phoenix-ph.png" alt=""></button><button title="Ajouter un serveur" data-config-link="synapseInviteUrl"><span>+</span></button>`;
    app.prepend(rail);
  }

  const nav=$('.syn-dash-tabs');
  if(nav && !nav.querySelector('[data-tab="welcome"]')){
    const community=nav.querySelector('.syn-nav-group:nth-of-type(5)') || nav;
    community.insertAdjacentHTML('afterbegin',`<button data-tab="welcome"><span>👋</span>Arrivées & départs</button><button data-tab="autoroles"><span>⛓</span>Rôles automatiques</button><button data-tab="securedroles"><span>🛡</span>Rôles sécurisés</button><button data-tab="messages"><span>✉</span>Messages & embeds</button><button data-tab="recurring"><span>◷</span>Messages récurrents</button><button data-tab="reports"><span>⚑</span>Signalements</button><button data-tab="suggestions"><span>💡</span>Suggestions</button><button data-tab="wordreact"><span>☺</span>Réactions de mots</button><button data-tab="birthdays"><span>🎂</span>Anniversaires</button>`);
  }

  const content=$('.syn-dash-content');
  if(content && !content.querySelector('[data-panel="welcome"]')){
    const toggle=(title,desc)=>`<label class="syn-pro-toggle"><span><b>${title}</b><small>${desc}</small></span><input type="checkbox"><i></i></label>`;
    const field=(label,ph)=>`<label class="syn-pro-field"><span>${label}</span><input placeholder="${ph}"></label>`;
    const panel=(id,kicker,title,body)=>`<section class="syn-panel syn-pro-panel" data-panel="${id}"><div class="syn-panel-head"><div><span class="v2-kicker">${kicker}</span><h2>${title}</h2></div></div>${body}</section>`;
    content.insertAdjacentHTML('beforeend',
      panel('welcome','COMMUNAUTÉ','Arrivées & départs',`<div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Message de bienvenue</h3><p>Choisissez le salon, le format et le contenu envoyé à l’arrivée.</p></div></div><div class="syn-pro-fields">${field('Salon','#bienvenue')}${field('Titre','Bienvenue {user} !')}${field('Image / bannière','URL ou média')}${field('Rôle donné','Membre')}</div><div class="syn-pro-toggle-grid">${toggle('Activer le message','Envoie automatiquement le message de bienvenue.')}${toggle('Embed personnalisé','Couleur, image, footer et boutons configurables.')}</div></div><div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Message de départ</h3><p>Même logique pour les membres qui quittent le serveur.</p></div></div><div class="syn-pro-fields">${field('Salon','#départs')}${field('Message','{user} a quitté le serveur.')}</div>${toggle('Activer les départs','Publier automatiquement un message de départ.')}</div>`)+
      panel('autoroles','RÔLES','Rôles automatiques',`<div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Attribution automatique</h3><p>Attribuez un ou plusieurs rôles à l’arrivée selon des conditions.</p></div></div><div class="syn-pro-table"><div class="head"><span>Condition</span><span>Rôle</span><span>Délai</span><span>État</span><span></span></div><div><span>Tous les membres</span><span>Membre</span><span>0 sec</span><span>Actif</span><button>Modifier</button></div></div><button class="syn-pro-add">+ Ajouter une règle</button></div>`)+
      panel('securedroles','SÉCURITÉ','Rôles sécurisés',`<div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Protection de rôles sensibles</h3><p>Empêchez l’attribution ou la modification non autorisée de certains rôles.</p></div></div><div class="syn-pro-toggle-grid">${toggle('Protéger les rôles staff','Surveille les attributions de rôles sensibles.')}${toggle('Retrait automatique','Retire le rôle si l’action n’est pas autorisée.')}${toggle('Journaliser les changements','Conserve qui a modifié quoi et quand.')}</div></div>`)+
      panel('messages','MESSAGES','Messages & embeds',`<div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Créer un message</h3><p>Texte, embed, image, sélecteur, boutons et rôle après interaction.</p></div></div><div class="syn-pro-fields">${field('Salon','#règlement')}${field('Titre','Règlement du serveur')}${field('Description','Votre texte...')}${field('Image','URL ou média')}</div><div class="syn-pro-toggle-grid">${toggle('Ajouter un bouton','Ex. “J’accepte le règlement”.')}${toggle('Donner un rôle après clic','Attribuer Membre après validation.')}${toggle('Ajouter un sélecteur','Menu déroulant avec plusieurs choix.')}${toggle('Supprimer la réaction précédente','Garder un seul choix actif.')}</div><button class="v2-btn v2-btn-violet">Enregistrer le message</button></div>`)+
      panel('recurring','AUTOMATISATION','Messages récurrents',`<div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Planification</h3><p>Publiez automatiquement des messages selon une fréquence.</p></div></div><div class="syn-pro-fields">${field('Salon','#annonces')}${field('Fréquence','Toutes les 6 heures')}${field('Message','Pensez à consulter...')}${field('Début','Aujourd’hui 18:00')}</div>${toggle('Activer la récurrence','Le message sera envoyé automatiquement.')}</div>`)+
      panel('reports','MODÉRATION','Signalements',`<div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Configuration des signalements</h3><p>Choisissez le salon, les rôles mentionnés et le workflow de prise en charge.</p></div></div><div class="syn-pro-fields">${field('Salon des signalements','#signalements')}${field('Rôles mentionnés','Modérateur, Admin')}${field('Message de confirmation','Merci pour votre signalement.')}${field('Limite par modérateur','3')}</div><div class="syn-pro-toggle-grid">${toggle('Réaction automatique','Ajoute une réaction sur le message signalé.')}${toggle('Regrouper les signalements','Fusionne les signalements concernant le même membre.')}${toggle('Conclusion en DM','Informe l’auteur du signalement du résultat.')}${toggle('Ouvrir un fil','Crée automatiquement un fil par signalement.')}</div></div>`)+
      panel('suggestions','COMMUNAUTÉ','Suggestions',`<div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Boîte à idées</h3><p>Votes, statuts, réponses staff et catégories de suggestions.</p></div></div><div class="syn-pro-toggle-grid">${toggle('Votes 👍 / 👎','Ajoute automatiquement les réactions de vote.')}${toggle('Réponse staff','Autorise une réponse officielle sous la suggestion.')}${toggle('Statut accepté/refusé','Permet de clôturer visuellement une suggestion.')}</div></div>`)+
      panel('wordreact','COMMUNAUTÉ','Réactions de mots',`<div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Déclencheurs</h3><p>Réagir ou répondre automatiquement à certains mots ou expressions.</p></div></div><div class="syn-pro-table"><div class="head"><span>Mot</span><span>Action</span><span>Réponse</span><span></span></div><div><span>bonjour</span><span>Réaction</span><span>👋</span><button>Modifier</button></div></div><button class="syn-pro-add">+ Ajouter un déclencheur</button></div>`)+
      panel('birthdays','COMMUNAUTÉ','Anniversaires',`<div class="syn-pro-section"><div class="syn-pro-section-head"><div><h3>Anniversaires des membres</h3><p>Message automatique, rôle temporaire et visibilité configurable.</p></div></div><div class="syn-pro-fields">${field('Salon','#anniversaires')}${field('Rôle temporaire','Anniversaire 🎂')}${field('Message','Joyeux anniversaire {user} !')}${field('Durée du rôle','24 h')}</div>${toggle('Activer les anniversaires','Publier automatiquement le jour J.')}</div>`)
    );
  }

  const bindTabs=()=>$$('[data-tab]',nav).forEach(btn=>{ if(btn.dataset.hubBound) return; btn.dataset.hubBound='1'; btn.addEventListener('click',()=>{ $$('[data-tab]',nav).forEach(b=>b.classList.toggle('active',b===btn)); $$('[data-panel]',content).forEach(p=>p.classList.toggle('active',p.dataset.panel===btn.dataset.tab)); history.replaceState(null,'',`#${btn.dataset.tab}`); window.scrollTo({top:0,behavior:'smooth'}); }); });
  bindTabs();
})();